apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: mainflux/manager:latest
        ports:
        - containerPort: 8180
        env:
        - name: MF_DB_HOST
          value: "mainflux-postgres"
        - name: MF_MANAGER_DB
          value: "mainflux"
        - name: MF_MANAGER_PORT
          value: "8180"
        - name: MF_MANAGER_SECRET
          value: "test-secret"
---
apiVersion: v1
kind: Service
metadata:
  name: manager
  labels:
    app: manager
spec:
  ports:
  - port: 8180
    targetPort: 8180
    protocol: TCP
    name: http
  selector:
    app: manager
  type: LoadBalancer
