apiVersion: apps/v1beta1 
kind: Deployment 
metadata:
  name: coap-adapter
  labels:
    component: coap-adapter 
spec:
  serviceName: coap-adapter
  replicas: 3
  template:
    metadata:
      labels:
        component: coap-adapter
    spec:
      containers:
      - name: mainflux-coap
        image: mainflux/coap
        imagePullPolicy: Always
        ports:
        - containerPort: 5683
        env:
        - name: COAP_ADAPTER_NATS_URL
          value: "nats://nats:4222"
---
apiVersion: v1 
kind: Service 
metadata:
  name: coap-adapter
  labels:
    component: coap-adapter 
spec:
  selector:
    component: coap-adapter
  ports:
  - protocol: UDP
    port: 5683
    targetPort: 5683 
  type: LoadBalancer
