apiVersion: v1 
kind: Service 
metadata:
  name: coap-adapter
  labels:
    component: coap-adapter 
spec:
  selector:
    component: coap-adapter
  ports:
  - protocol: UDP
    port: 5683
    targetPort: 5683 
  type: LoadBalancer
--- 
apiVersion: apps/v1beta1 
kind: StatefulSet 
metadata:
  name: coap-adapter
  labels:
    component: coap-adapter 
spec:
  serviceName: coap-adapter
  replicas: 3
  template:
    metadata:
      labels:
        component: coap-adapter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: component
                  operator: In
                  values:
                    - coap-adapter
            topologyKey: kubernetes.io/hostname
      containers:
      - name: mainflux-coap
        image: mainflux/coap
        imagePullPolicy: Always
        ports:
        - containerPort: 5683
        env:
        - name: COAP_ADAPTER_NATS_URL
          value: "nats://nats:4222"

