apiVersion: v1 
kind: Service 
metadata:
  name: normalizer
  labels:
    component: normalizer 
spec:
  selector:
    component: normalizer
  ports:
  - port: 8181
    targetPort: 8181 
  clusterIP: None
--- 
apiVersion: apps/v1beta1 
kind: StatefulSet 
metadata:
  name: normalizer
  labels:
    component: normalizer
spec:
  serviceName: normalizer
  replicas: 3
  template:
    metadata:
      labels:
        component: normalizer
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: component
                  operator: In
                  values:
                    - normalizer
            topologyKey: kubernetes.io/hostname
      containers:
      - name: mainflux-normalizer
        image: mainflux/normalizer:latest
        imagePullPolicy: Always
        env:
        - name: MF_NATS_URL
          value: "nats://nats:4222"
        - name: MF_NORMALIZER_PORT
          value: "8181"
