apiVersion: v1
kind: PersistentVolume
metadata:
  name: mainflux-postgres-data-disk
  labels:
    name: mainflux-postgres-data-disk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/postgres-0
  persistentVolumeReclaimPolicy: Recycle